services:
    prodserver:
        container_name: prodserver
        build:
            context: .
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
        command: >
            sh -c "echo 'âœ… Production instance running on http://localhost:3000' &&
                   pnpm run start"
        networks:
            - app-network

    devserver:
        container_name: devserver
        build:
            context: .
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development
        command: >
            sh -c "echo 'ğŸ›  Development instance running on http://localhost:3001' &&
                   pnpm run dev"
        volumes:
            - .:/app
            - /app/node_modules
        networks:
            - app-network

    webserver:
        container_name: webserver
        build:
            context: ./nginx
        depends_on:
            - prodserver
        ports:
            - '8080:80'
        command: sh -c "echo 'ğŸŒ Hosted Nginx instance is running on http://localhost:8080' && nginx -g 'daemon off;'"
        networks:
            - app-network
        restart: unless-stopped

networks:
    app-network:
        driver: bridge
